# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f71c5e2d2d67cae82dc3145e2ac9c75b09b9362c44d210e20e634cb0b4f0e7a2fff4b7e9d66087bec5f5a63f336fc452f2569b8c690851a3095c3c0264bba302

test:
  secret_key_base: c36130841b7d43e3630bbf7dd0489f8ba8f8aa281a462a3546f67932409035875656dec140636932d4bebdbe71199557472af8a5b67a19475e66ec21d19db536

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
